"""Pin the manuscript's phase-diagram curves to the computed normal form data.

Figure ``fig:app1_phase`` of the paper is not generated by this package: it is
drawn directly in pgfplots from polynomial coefficients transcribed by hand into
``paper/O2sym.tex``.  Nothing in the build would notice if those numbers drifted
away from what ``o2sym.coverage`` computes -- the document would still compile
and the figure would still look plausible.  This test closes that gap.

Each region boundary is a conic in the ``(g11, g22)``-plane at ``g21 = 1``.
Writing ``x = g11``, ``y = g22``, the quadratic form ``g^T M g`` becomes

    M[2,2] y^2 + (2 M[0,2] x + 2 M[1,2]) y + (M[0,0] x^2 + 2 M[0,1] x + M[1,1])

and the three plotted curves are the roots of this for ``M = A`` (solid,
``zeta_R = 0``), ``M = A + B`` (dashed) and ``M = A - B`` (dotted).  Only the
ratios matter, since each ``\\addplot`` uses the quadratic formula on integers
scaled to clear denominators; the test therefore normalises on the ``y^2`` term.

If this test fails, either the figure or the code changed: reconcile them before
submitting, and see the note at ``O2sym.tex`` Code availability.
"""
from __future__ import annotations

import pytest

from o2sym.coverage import extract_quadratic_forms

# Transcribed from paper/O2sym.tex, figure fig:app1_phase, at a=1/2, c=1, g21=1.
# Order: (y^2, y*x, y*1, x^2, x, 1).  Read off the \addplot quadratic-formula
# arguments, where the denominator is 2a, the leading bracket is -b, and the
# term under the radical is b^2 - 4ac.
A_C = 0.5, 1.0
CURVES = {
    "solid (zeta_R = 0)": (213, 285, 321, 690, 723, 24),
    "dashed (zeta_R + xi_R = 0)": (14517, -6570, -3303, 17001, 25227, 504),
    "dotted (zeta_R - xi_R = 0)": (-5571, 18540, 16785, 11979, 5139, 504),
}


def _conic(M):
    """Coefficients of g^T M g with g = (x, 1, y), ordered as in CURVES."""
    return (M[2, 2], 2 * M[0, 2], 2 * M[1, 2], M[0, 0], 2 * M[0, 1], M[1, 1])


@pytest.mark.parametrize("name", list(CURVES))
def test_phase_diagram_coefficients_match_code(name):
    A, B = extract_quadratic_forms(*A_C)
    M = {"solid (zeta_R = 0)": A,
         "dashed (zeta_R + xi_R = 0)": A + B,
         "dotted (zeta_R - xi_R = 0)": A - B}[name]

    expected = CURVES[name]
    computed = _conic(M)
    scale = expected[0] / computed[0]

    for got, want, label in zip(computed, expected, ("y^2", "yx", "y", "x^2", "x", "1")):
        assert got * scale == pytest.approx(want, abs=1e-6), (
            f"{name}: coefficient of {label} is {got * scale!r} in the code "
            f"but {want!r} in O2sym.tex"
        )
